// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: brick_collection.
// - Entity ID: 102019c68e565fe75d7af5b1c139a005a9f.
// - Entity Version: 102019c68e565fe745cbb6af0c5c375337b.
// - Task ID: 6993af746bd96e563a126d72.
// - Task Root ID: 6993af746bd96e563a126d72.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for BrickCollectionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface BrickCollectionModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  brick_type: string;
  color: string;
  quantity: number;
}

/**
 * ORM class for BrickCollection entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class BrickCollectionORM {
  private static instance: BrickCollectionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019c68e565fe75d7af5b1c139a005a9f';
    this.entityName = 'brick_collection';
    this.entityVersion = '102019c68e565fe745cbb6af0c5c375337b';
    this.taskId = '6993af746bd96e563a126d72';
    this.taskRootId = '6993af746bd96e563a126d72';
  }

  /**
   * Get singleton instance of BrickCollectionORM
   */
  public static getInstance(): BrickCollectionORM {
    if (!BrickCollectionORM.instance) {
      BrickCollectionORM.instance = new BrickCollectionORM();
    }
    
    return BrickCollectionORM.instance;
  }

  /**
   * Get brick_collection by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getBrickCollectionByIDs(ids: string[]): Promise<BrickCollectionModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete brick_collection by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteBrickCollectionByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all BrickCollection records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllBrickCollection(): Promise<BrickCollectionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new BrickCollection record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertBrickCollection(data: BrickCollectionModel[]): Promise<BrickCollectionModel[]> {
    const structured = data.map((item) => CreateData(BrickCollectionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all BrickCollection records
   */
  async purgeAllBrickCollection(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List BrickCollection records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listBrickCollection(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[BrickCollectionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get brick_collection by Id index
   * This function gets data by index.
   */
  async getBrickCollectionById(
    id: string,
  ): Promise<BrickCollectionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) brick_collection by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBrickCollectionById(
    id: string,
    data: BrickCollectionModel
  ): Promise<BrickCollectionModel[]> {
    const index = createIndexId(
      id
    );

    const values = BrickCollectionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete brick_collection by Id index
   */
  async deleteBrickCollectionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get brick_collection by UserId index
   * This function gets data by index.
   */
  async getBrickCollectionByUserId(
    user_id: string,
  ): Promise<BrickCollectionModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) brick_collection by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBrickCollectionByUserId(
    user_id: string,
    data: BrickCollectionModel
  ): Promise<BrickCollectionModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = BrickCollectionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete brick_collection by UserId index
   */
  async deleteBrickCollectionByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get brick_collection by BrickTypeColorUserId index
   * This function gets data by index.
   */
  async getBrickCollectionByBrickTypeColorUserId(
    brick_type: string,
    color: string,
    user_id: string,
  ): Promise<BrickCollectionModel[]> {
    const index = createIndexBrickTypeColorUserId(
      brick_type,
      color,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) brick_collection by BrickTypeColorUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBrickCollectionByBrickTypeColorUserId(
    brick_type: string,
    color: string,
    user_id: string,
    data: BrickCollectionModel
  ): Promise<BrickCollectionModel[]> {
    const index = createIndexBrickTypeColorUserId(
      brick_type,
      color,
      user_id
    );

    const values = BrickCollectionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete brick_collection by BrickTypeColorUserId index
   */
  async deleteBrickCollectionByBrickTypeColorUserId(
    brick_type: string,
    color: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexBrickTypeColorUserId(
      brick_type,
      color,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get brick_collection by DataCreator index
   * This function gets data by index.
   */
  async getBrickCollectionByDataCreator(
    data_creator: string,
  ): Promise<BrickCollectionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) brick_collection by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBrickCollectionByDataCreator(
    data_creator: string,
    data: BrickCollectionModel
  ): Promise<BrickCollectionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = BrickCollectionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete brick_collection by DataCreator index
   */
  async deleteBrickCollectionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get brick_collection by DataUpdater index
   * This function gets data by index.
   */
  async getBrickCollectionByDataUpdater(
    data_updater: string,
  ): Promise<BrickCollectionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) brick_collection by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBrickCollectionByDataUpdater(
    data_updater: string,
    data: BrickCollectionModel
  ): Promise<BrickCollectionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = BrickCollectionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete brick_collection by DataUpdater index
   */
  async deleteBrickCollectionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to BrickCollectionModel data array
   */
  private resultToData(values: Data[]): BrickCollectionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return BrickCollectionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as BrickCollectionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized BrickCollectionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is BrickCollectionModel => item !== null);
  }
}

/**
 * Convert BrickCollectionModel data to Value array
 */
function BrickCollectionModelToValues(data: BrickCollectionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'brick_type', type: DataType.string, defaultValue: '' },
    { key: 'color', type: DataType.string, defaultValue: '' },
    { key: 'quantity', type: DataType.number, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof BrickCollectionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to BrickCollectionModel data
 */
function BrickCollectionModelFromValues(values: Value[]): BrickCollectionModel {
  const data: Partial<BrickCollectionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'brick_type':
        data.brick_type = ParseValue(value, DataType.string) as string;
        break;
      case 'color':
        data.color = ParseValue(value, DataType.string) as string;
        break;
      case 'quantity':
        data.quantity = ParseValue(value, DataType.number) as number;
        break;
    }
  }
  
  return data as BrickCollectionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for BrickTypeColorUserId fields
 */
function createIndexBrickTypeColorUserId(
  brick_type: string,
  color: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, brick_type, 'brick_type'),
    CreateValue(DataType.string, color, 'color'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['brick_type', 'color', 'user_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default BrickCollectionORM;