// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: chat_message.
// - Entity ID: 102019c68e565fe778fa002d55cb799c419.
// - Entity Version: 102019c68e565fe745cbb6af0c5c375337b.
// - Task ID: 6993af746bd96e563a126d72.
// - Task Root ID: 6993af746bd96e563a126d72.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for ChatMessageRole
 */
export enum ChatMessageRole {
  Unspecified = 0,
  User = 1,
  Assistant = 2,
}



/**
 * Interface for ChatMessageModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ChatMessageModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  session_id: string;
  role: ChatMessageRole;
  text_content: string;
}

/**
 * ORM class for ChatMessage entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ChatMessageORM {
  private static instance: ChatMessageORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019c68e565fe778fa002d55cb799c419';
    this.entityName = 'chat_message';
    this.entityVersion = '102019c68e565fe745cbb6af0c5c375337b';
    this.taskId = '6993af746bd96e563a126d72';
    this.taskRootId = '6993af746bd96e563a126d72';
  }

  /**
   * Get singleton instance of ChatMessageORM
   */
  public static getInstance(): ChatMessageORM {
    if (!ChatMessageORM.instance) {
      ChatMessageORM.instance = new ChatMessageORM();
    }
    
    return ChatMessageORM.instance;
  }

  /**
   * Get chat_message by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getChatMessageByIDs(ids: string[]): Promise<ChatMessageModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete chat_message by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteChatMessageByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all ChatMessage records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllChatMessage(): Promise<ChatMessageModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new ChatMessage record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertChatMessage(data: ChatMessageModel[]): Promise<ChatMessageModel[]> {
    const structured = data.map((item) => CreateData(ChatMessageModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all ChatMessage records
   */
  async purgeAllChatMessage(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List ChatMessage records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listChatMessage(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ChatMessageModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get chat_message by Id index
   * This function gets data by index.
   */
  async getChatMessageById(
    id: string,
  ): Promise<ChatMessageModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) chat_message by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setChatMessageById(
    id: string,
    data: ChatMessageModel
  ): Promise<ChatMessageModel[]> {
    const index = createIndexId(
      id
    );

    const values = ChatMessageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete chat_message by Id index
   */
  async deleteChatMessageById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get chat_message by SessionId index
   * This function gets data by index.
   */
  async getChatMessageBySessionId(
    session_id: string,
  ): Promise<ChatMessageModel[]> {
    const index = createIndexSessionId(
      session_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) chat_message by SessionId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setChatMessageBySessionId(
    session_id: string,
    data: ChatMessageModel
  ): Promise<ChatMessageModel[]> {
    const index = createIndexSessionId(
      session_id
    );

    const values = ChatMessageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete chat_message by SessionId index
   */
  async deleteChatMessageBySessionId(
    session_id: string
  ): Promise<void> {
    const index = createIndexSessionId(
      session_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get chat_message by UserId index
   * This function gets data by index.
   */
  async getChatMessageByUserId(
    user_id: string,
  ): Promise<ChatMessageModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) chat_message by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setChatMessageByUserId(
    user_id: string,
    data: ChatMessageModel
  ): Promise<ChatMessageModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = ChatMessageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete chat_message by UserId index
   */
  async deleteChatMessageByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get chat_message by CreateTime index
   * This function gets data by index.
   */
  async getChatMessageByCreateTime(
    create_time: string,
  ): Promise<ChatMessageModel[]> {
    const index = createIndexCreateTime(
      create_time
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) chat_message by CreateTime index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setChatMessageByCreateTime(
    create_time: string,
    data: ChatMessageModel
  ): Promise<ChatMessageModel[]> {
    const index = createIndexCreateTime(
      create_time
    );

    const values = ChatMessageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete chat_message by CreateTime index
   */
  async deleteChatMessageByCreateTime(
    create_time: string
  ): Promise<void> {
    const index = createIndexCreateTime(
      create_time
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get chat_message by DataCreator index
   * This function gets data by index.
   */
  async getChatMessageByDataCreator(
    data_creator: string,
  ): Promise<ChatMessageModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) chat_message by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setChatMessageByDataCreator(
    data_creator: string,
    data: ChatMessageModel
  ): Promise<ChatMessageModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ChatMessageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete chat_message by DataCreator index
   */
  async deleteChatMessageByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get chat_message by DataUpdater index
   * This function gets data by index.
   */
  async getChatMessageByDataUpdater(
    data_updater: string,
  ): Promise<ChatMessageModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) chat_message by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setChatMessageByDataUpdater(
    data_updater: string,
    data: ChatMessageModel
  ): Promise<ChatMessageModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ChatMessageModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete chat_message by DataUpdater index
   */
  async deleteChatMessageByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ChatMessageModel data array
   */
  private resultToData(values: Data[]): ChatMessageModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ChatMessageModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ChatMessageModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ChatMessageModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ChatMessageModel => item !== null);
  }
}

/**
 * Convert ChatMessageModel data to Value array
 */
function ChatMessageModelToValues(data: ChatMessageModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'session_id', type: DataType.string, defaultValue: '' },
    { key: 'role', type: DataType.enumeration, defaultValue: 0 },
    { key: 'text_content', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ChatMessageModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ChatMessageModel data
 */
function ChatMessageModelFromValues(values: Value[]): ChatMessageModel {
  const data: Partial<ChatMessageModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'session_id':
        data.session_id = ParseValue(value, DataType.string) as string;
        break;
      case 'role':
        data.role = ParseValue(value, DataType.enumeration) as ChatMessageRole;
        break;
      case 'text_content':
        data.text_content = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as ChatMessageModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for SessionId fields
 */
function createIndexSessionId(
  session_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, session_id, 'session_id'),
  ];

  return {
    fields: ['session_id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for CreateTime fields
 */
function createIndexCreateTime(
  create_time: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, create_time, 'create_time'),
  ];

  return {
    fields: ['create_time'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default ChatMessageORM;