// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: saved_build.
// - Entity ID: 102019c68e565fe78bbba35a8920a9cfd04.
// - Entity Version: 102019c68e565fe745cbb6af0c5c375337b.
// - Task ID: 6993af746bd96e563a126d72.
// - Task Root ID: 6993af746bd96e563a126d72.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for SavedBuildDifficultyLevel
 */
export enum SavedBuildDifficultyLevel {
  Unspecified = 0,
  Easy = 1,
  Medium = 2,
  Hard = 3,
}



/**
 * Interface for SavedBuildModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface SavedBuildModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  title: string;
  description?: string | null;
  difficulty_level: SavedBuildDifficultyLevel;
  brick_count: number;
  image_url?: string | null;
}

/**
 * ORM class for SavedBuild entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class SavedBuildORM {
  private static instance: SavedBuildORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019c68e565fe78bbba35a8920a9cfd04';
    this.entityName = 'saved_build';
    this.entityVersion = '102019c68e565fe745cbb6af0c5c375337b';
    this.taskId = '6993af746bd96e563a126d72';
    this.taskRootId = '6993af746bd96e563a126d72';
  }

  /**
   * Get singleton instance of SavedBuildORM
   */
  public static getInstance(): SavedBuildORM {
    if (!SavedBuildORM.instance) {
      SavedBuildORM.instance = new SavedBuildORM();
    }
    
    return SavedBuildORM.instance;
  }

  /**
   * Get saved_build by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getSavedBuildByIDs(ids: string[]): Promise<SavedBuildModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete saved_build by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteSavedBuildByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all SavedBuild records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllSavedBuild(): Promise<SavedBuildModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new SavedBuild record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertSavedBuild(data: SavedBuildModel[]): Promise<SavedBuildModel[]> {
    const structured = data.map((item) => CreateData(SavedBuildModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all SavedBuild records
   */
  async purgeAllSavedBuild(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List SavedBuild records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listSavedBuild(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[SavedBuildModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get saved_build by Id index
   * This function gets data by index.
   */
  async getSavedBuildById(
    id: string,
  ): Promise<SavedBuildModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) saved_build by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSavedBuildById(
    id: string,
    data: SavedBuildModel
  ): Promise<SavedBuildModel[]> {
    const index = createIndexId(
      id
    );

    const values = SavedBuildModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete saved_build by Id index
   */
  async deleteSavedBuildById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get saved_build by UserId index
   * This function gets data by index.
   */
  async getSavedBuildByUserId(
    user_id: string,
  ): Promise<SavedBuildModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) saved_build by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSavedBuildByUserId(
    user_id: string,
    data: SavedBuildModel
  ): Promise<SavedBuildModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = SavedBuildModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete saved_build by UserId index
   */
  async deleteSavedBuildByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get saved_build by DifficultyLevel index
   * This function gets data by index.
   */
  async getSavedBuildByDifficultyLevel(
    difficulty_level: SavedBuildDifficultyLevel,
  ): Promise<SavedBuildModel[]> {
    const index = createIndexDifficultyLevel(
      difficulty_level
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) saved_build by DifficultyLevel index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSavedBuildByDifficultyLevel(
    difficulty_level: SavedBuildDifficultyLevel,
    data: SavedBuildModel
  ): Promise<SavedBuildModel[]> {
    const index = createIndexDifficultyLevel(
      difficulty_level
    );

    const values = SavedBuildModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete saved_build by DifficultyLevel index
   */
  async deleteSavedBuildByDifficultyLevel(
    difficulty_level: SavedBuildDifficultyLevel
  ): Promise<void> {
    const index = createIndexDifficultyLevel(
      difficulty_level
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get saved_build by DataCreator index
   * This function gets data by index.
   */
  async getSavedBuildByDataCreator(
    data_creator: string,
  ): Promise<SavedBuildModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) saved_build by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSavedBuildByDataCreator(
    data_creator: string,
    data: SavedBuildModel
  ): Promise<SavedBuildModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = SavedBuildModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete saved_build by DataCreator index
   */
  async deleteSavedBuildByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get saved_build by DataUpdater index
   * This function gets data by index.
   */
  async getSavedBuildByDataUpdater(
    data_updater: string,
  ): Promise<SavedBuildModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) saved_build by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSavedBuildByDataUpdater(
    data_updater: string,
    data: SavedBuildModel
  ): Promise<SavedBuildModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = SavedBuildModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete saved_build by DataUpdater index
   */
  async deleteSavedBuildByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to SavedBuildModel data array
   */
  private resultToData(values: Data[]): SavedBuildModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return SavedBuildModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as SavedBuildModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized SavedBuildModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is SavedBuildModel => item !== null);
  }
}

/**
 * Convert SavedBuildModel data to Value array
 */
function SavedBuildModelToValues(data: SavedBuildModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'title', type: DataType.string, defaultValue: '' },
    { key: 'description', type: DataType.string, defaultValue: null },
    { key: 'difficulty_level', type: DataType.enumeration, defaultValue: 0 },
    { key: 'brick_count', type: DataType.number, defaultValue: 0 },
    { key: 'image_url', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof SavedBuildModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to SavedBuildModel data
 */
function SavedBuildModelFromValues(values: Value[]): SavedBuildModel {
  const data: Partial<SavedBuildModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'title':
        data.title = ParseValue(value, DataType.string) as string;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string | null;
        break;
      case 'difficulty_level':
        data.difficulty_level = ParseValue(value, DataType.enumeration) as SavedBuildDifficultyLevel;
        break;
      case 'brick_count':
        data.brick_count = ParseValue(value, DataType.number) as number;
        break;
      case 'image_url':
        data.image_url = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as SavedBuildModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for DifficultyLevel fields
 */
function createIndexDifficultyLevel(
  difficulty_level: SavedBuildDifficultyLevel
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, difficulty_level, 'difficulty_level'),
  ];

  return {
    fields: ['difficulty_level'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default SavedBuildORM;